use static_files::resource_dir;
// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    println!("cargo:rerun-if-changed=templates");
    println!("cargo:rerun-if-changed=static");
    #[allow(clippy::expect_used)]
    resource_dir("./static")
        .build()
        .expect("Failed to build static files");
}
