CREATE TABLE IF NOT EXISTS users(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  userid TEXT UNIQUE NOT NULL,
  name VARCHAR(250),
  email VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS webauthn_credentials(
  id TEXT UNIQUE NOT NULL,
  passkey TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
